### PR TITLE
Avalonia version now accepts a stream directly if needed

### PR DESCRIPTION
**Pull request by xafero**

### CODE REVIEW

**Comment by whistyun** [comment]
@xafero 
Are there any samples where Image.Source receives the stream directly?
I try bellow xaml but it occures build failure.

```xml
<!-- 
    xmlns:st="using:System"
    xmlns:io="using:System.IO"
-->
<!-- It seems that Image.Source does not accept a stream. -->
<Image>
  <Image.Source>
    <io:FileStream>
      <x:Arguments>
        <st:String>D:\WpfAnimatedGif\DemoForAvaloniaUI\Assets\UnsupportImageFormat.bmp</st:String>
        <io:FileMode>Open</io:FileMode>
      </x:Arguments>
    </io:FileStream>
  </Image.Source>
</Image>

<!-- On the other hand, strings are accepted. -->
<Image>
  <Image.Source>
    <st:String>avares://AnimatedImageTest.Avalonia/Assets/BouncingBeachBall.png</st:String>
  </Image.Source>
</Image>


```

**Comment by xafero** [comment]
Small change to make it directly usable:

`--- a/AnimatedImage.Avalonia/ImageBehavior.cs
+++ b/AnimatedImage.Avalonia/ImageBehavior.cs
@@ -81,9 +81,17 @@ namespace AnimatedImage.Avalonia

         /// Sets the value of the <c>AnimatedSource</c> attached property for the specified object.
         /// </summary>
         /// <param name="obj">The element on which to set the property value.</param>

-        /// <param name="uri">The animated image to display.</param>
-        public static void SetAnimatedSource(AvaloniaObject obj, Uri uri)
-            => ((Image)obj).SetValue(AnimatedSourceProperty, new BitmapUri(uri));

+        /// <param name="source">The animated image to display.</param>
+        public static void SetAnimatedSource(AvaloniaObject obj, object source)
+        {
+            if (source is string str)
+                source = new BitmapUri(new Uri(str));
+            else if (source is Uri uri) 
+                source = new BitmapUri(uri);
+            else if (source is Stream stream) 
+                source = new BitmapStream(stream);
+            ((Image)obj).SetValue(AnimatedSourceProperty, source);
+        }
 `

**Comment by xafero** [comment]
image

Example for using this

**Comment by whistyun** [comment]
Is the intention not to conform to Image's Source specification, but to be able to receive Streams in xaml and bindings?
Also Image.Source (not AnimatedSource) dose not accept a Stream in Avalonia 11.0.7 as well?

**Comment by xafero** [comment]
Frankly, I don't care about Avalonia's specs. WPF is their target, they should fix it.

I'm coming from the angle of WPF, and it's BitmapSource, being able to load URIs - sure, but also putting byte[] into it:

https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.imaging.bitmapsource?view=windowsdesktop-8.0

To be more concrete, I see two applications of this broader concept in the library:
1) Show a spinner Gif and writing the Avalonia Resource URL in XAML directly.
2) Load some arbitrary foreign file from network or wherever, and show by using a Binding named Image and putting this Stream (or byte[] MemoryStream) into that.

**Comment by xafero** [comment]
> Is the intention not to conform to Image's Source specification, but to be able to receive Streams in xaml and bindings? Also Image.Source (not AnimatedSource) dose not accept a Stream in Avalonia 11.0.7 as well?

I saw in WPF part of the library that loading of arbitrary image (GIF) data is possible, by using BitmapSource, but not in Avalonia's version. So I changed it. In my opinion, Avalonia team (which did not answer me at all) has to come closer in allowing more flexibility.

**Pull request merged**
